{
 "title": "Pizza Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Pizza Sales / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sales_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\", type=\"http\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Authentication Attempts / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(auth_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{type}} Usage"
    }
   ]
  },
  {
   "title": "Database Query Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\", type=\"db\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Unhandled Exception Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\", type=\"unhandledError\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "creation_current{source=\"jwt-pizza-service\", type=\"Latency\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pizza Creation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(creation_total{source=\"jwt-pizza-service\", type=\"Failures\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Factory Service Request Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\", type=\"factory\"} |= `` | json"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}